version: "3.9"

services:
  frontend:
    image: 637423223864.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest
    container_name: innovatech-frontend
    restart: unless-stopped
    ports:
      - "80:80"
