server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Servir archivos estáticos
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Health check del frontend
    location /health {
        return 200 '{"status":"ok","servicio":"Frontend Innovatech"}';
        add_header Content-Type application/json;
    }
}
